### PR TITLE
Multiple Benificiary visit-api modified for all visit category

### PR DESCRIPTION
**Pull request by indraniBan**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.  

# Type of change  

- [ ] Bug fix  
- [ ] New feature  
- [ ] Enhancement  
- [ ] Refactoring  
- [ ] Documentation  
- [ ] Other ( please specify )  

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by devikasuresh20 — APPROVED** [review]

**Review by drtechie — CHANGES_REQUESTED** [review]
@indraniBan 

Here any error that happens during booking is interpreted as the slot is already booked.
How are "Error while booking slot." and "Slot already booked" in the same context?

Secondly, using error message comparison is not a good idea.
It's best to raise a specific exception for an already booked slot and catch the same.

cc: @devikasuresh20 

Also, please complete the PR template.

**Comment by drtechie** [comment]
Also not sure what the 5000 error code is.
Is this an HTTP status code? I think you meant 500.

**Comment by drtechie** [comment]
The code that prepares `jsnOBJ` is repeated in try-and-catch blocks. There is potential to make it DRY.

**Review by ravishanigarapu — APPROVED** [review]
looks ok

**Review by ravishanigarapu — APPROVED** [review]
looks ok

**Review by helenKaryamsetty — COMMENTED** [review]
checked by ravi

**Review by helenKaryamsetty — APPROVED** [review]

**Review by drtechie — APPROVED** [review]

**Pull request merged**
